# Parameters
UserIdParam:
  name: id
  in: path
  required: true
  description: MongoDB ObjectId of the user
  schema:
    type: string
    format: objectid
    pattern: '^[0-9a-fA-F]{24}$'
    example: '507f1f77bcf86cd799439011'

ListingIdParam:
  name: id
  in: path
  required: true
  description: MongoDB ObjectId of the listing
  schema:
    type: string
    format: objectid
    pattern: '^[0-9a-fA-F]{24}$'
    example: '507f1f77bcf86cd799439012'

LimitParam:
  name: limit
  in: query
  description: Maximum number of results to return
  schema:
    type: integer
    minimum: 1
    maximum: 100
    default: 10
    example: 20

OffsetParam:
  name: offset
  in: query
  description: Number of results to skip for pagination
  schema:
    type: integer
    minimum: 0
    default: 0
    example: 0
