openapi: 3.1.0
paths:
  /listings:
    get:
      tags:
        - Listings
      summary: Get all listings
      description: Retrieve all real estate listings from the database
      responses:
        200:
          description: Successfully retrieved all listings
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Listing'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      tags:
        - Listings
      summary: Create a new listing
      description: Create a new real estate listing
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListingCreate'
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 'Beautiful Ocean View House'
                price:
                  type: number
                  example: 750000
                image:
                  type: string
                  format: binary
                  description: Image file upload
      responses:
        201:
          description: Listing created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingResponse'
        400:
          description: Bad request - validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        422:
          description: Unprocessable entity - empty request body
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /listings/{id}:
    get:
      tags:
        - Listings
      summary: Get listing by ID
      description: Retrieve a specific real estate listing by its ID
      parameters:
        - $ref: '#/components/parameters/ListingIdParam'
      responses:
        200:
          description: Successfully retrieved the listing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Listing'
        400:
          description: Bad request - invalid listing ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Listing not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    put:
      tags:
        - Listings
      summary: Update listing by ID
      description: Update a specific real estate listing by its ID
      parameters:
        - $ref: '#/components/parameters/ListingIdParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ListingUpdate'
          multipart/form-data:
            schema:
              type: object
              properties:
                title:
                  type: string
                  example: 'Updated Beautiful Ocean View House'
                price:
                  type: number
                  example: 850000
                image:
                  type: string
                  format: binary
                  description: New image file upload
      responses:
        200:
          description: Listing updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingResponse'
        400:
          description: Bad request - invalid listing ID or validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Listing not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Listings
      summary: Delete listing by ID
      description: Delete a specific real estate listing by its ID
      parameters:
        - $ref: '#/components/parameters/ListingIdParam'
      responses:
        200:
          description: Listing deleted successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListingResponse'
        400:
          description: Bad request - invalid listing ID
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        404:
          description: Listing not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        500:
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
