openapi: 3.1.0
info:
  title: Real Estate API
  description: |
    A comprehensive API for managing real estate listings and user accounts.

    ## Features
    - User account management with profile image upload
    - Real estate listing CRUD operations
    - Image upload support via Cloudinary
    - Form data and JSON request support
    - Comprehensive error handling

    ## Authentication
    Currently, this API doesn't require authentication, but it's ready for implementation.

    ## Image Upload
    The API supports multiple image input methods:
    - File upload (multipart/form-data)
    - Image URL
    - Default system images

  version: 1.0.0
  contact:
    name: Real Estate Development Team
    email: dev@realestate.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: http://localhost:3000
    description: Development server
  - url: https://api.realestate.com
    description: Production server (when deployed)

tags:
  - name: Users
    description: User account management operations
  - name: Listings
    description: Real estate listing management operations
  - name: Health
    description: API health and status endpoints

paths:
  /:
    get:
      tags:
        - Health
      summary: API Health Check
      description: Check if the API server is running and healthy
      responses:
        200:
          description: Server is running successfully
          content:
            text/plain:
              schema:
                type: string
                example: 'server is working on 3000'
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Internal server error'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication (future implementation)
